# templates/persistent-volume.yaml
{{- if .Values.persistentVolume.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.persistentVolume.fileSystemId }}::{{ .Values.persistentVolume.endpointId }}
{{- end }}

---
# templates/pvc.yaml
{{- if .Values.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claimName }}
  labels:
    {{- include "helm-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClass }}
  resources:
    requests:
      storage: 1Mi
  volumeName: {{ .Values.persistentVolume.name }}  # Explicitly bind to PV
{{- end }}