apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "helm-api.labels" . | nindent 4 }}
type: Opaque
stringData:  # Use stringData to read from env vars
 CREATE_API_KEY: ${HELM_API_CREATE_API_KEY}
 DELETE_API_KEY: ${HELM_API_DELETE_API_KEY}
 UPDATE_API_KEY: ${HELM_API_UPDATE_API_KEY}