# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mariadb.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mariadb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mariadb.serviceAccountName" . }}
      {{- if .Values.initScripts }}
      initContainers:
        - name: init-scripts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['sh', '-c', 'cp /docker-entrypoint-initdb.d/* /init-scripts/']
          volumeMounts:
            - name: init-scripts
              mountPath: /init-scripts
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      {{- end }}
      containers:
        - name: mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.noAuth }}
            - --skip-grant-tables
            {{- end }}
          ports:
            - name: mysql
              containerPort: 3306
          env:
            {{- if .Values.noAuth }}
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "yes"
            {{- else }}
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}-creds
                  key: root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.database.name }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}-creds
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}-creds
                  key: password
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            {{- if not .Values.noAuth }}
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
            {{- end }}
            {{- if .Values.initScripts }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mariadb-admin ping -uroot"
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mariadb-admin status -uroot"
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if not .Values.noAuth }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "mariadb.fullname" . }}-secrets
        {{- end }}
        {{- if .Values.initScripts }}
        - name: init-scripts
          emptyDir: {}
        - name: custom-init-scripts
          configMap:
            name: {{ include "mariadb.fullname" . }}-init
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ebs-gp3-helm-api
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
